### ISSUE TITLE
Concepção do Jogo

### ISSUE THREAD

**Issue by alanos005** [El-Gato-Gordo/Jogo#1]
Concepção do Jogo:

Jogo 2D, estilo pixelizado de combate de plataforma.

Resumo da história:
Um mago aleijado, sem poder andar mais e um cavaleiro fatalmente ferido - cego - se encontram por coincidência numa floresta, têm um breve diálogo. O mago alivia as dores do cavaleiro, e em troca o cavaleiro, guiado pelo mago, o carrega nas costas para fora da floresta.
Após saírem da floresta, partem em busca de alguma forma de se curarem.

Um pequeno mago se encontra escapando de uma criatura sombria em meio a uma grande floresta. Quando acaba encurralado, um cavaleiro misterioso surge e recebe o ataque em seu lugar, ocasionando na perda de sua energia vital e satisfazendo a criatura, que acaba por desaparecer do local. Ao observar a cena, o mago transforma a armadura vazia do cavaleiro em uma carapaça para a sua consciência. O cavaleiro com sua consciência presa a sua armadura, e o pequeno mago, então, partem em busca do que foi roubado pela criatura. 

Mecânicas:

`HP`: Governa a vitalidade tanto do mago quanto do cavaleiro
`MANA`: Permite conjurar feitiços

- Cavaleiro:
1. `A e D`: Andar 
2. `A ou D duas vezes rapidamente`: Corrida
3. `S`: Agacha
4. `J`: Atacar (combo de três golpes)
5. `J enquanto corre`: Corte vertical (Salto + Corte para baixo)
6. `J no ar`: Golpe aéreo (Corte horizontal)
7. `J + S no ar`: Estocada Pesada (Enfia espada no chão)
8. `J durante investida mágica`: Estocada aérea 
9. `J durante estrela cadente`: Meteoro azul
10. `K`: Esquiva (Muito lento para se recuperar)

- Mago:
1. `SETAS DIRECIONAIS`: Direcional de Feitiços
2. `num0`: Aparar (Atordoa inimigos brevemente e os empurra um pouco)
3. `num1`: Feitiço de Projétil [O mago conjura um projétil mágico para ataques à longa distância; custa mana]
4. `num2`: Espada Espectral [O mago conjura uma espada mágica à frente do cavaleiro para desferir um golpe; só pode ser conjurada após um golpe do cavaleiro e custa mana]
5. `num3 + CIMA`: Salto mágico
6. `num3 + LADO no ar`: Investida mágica
7. `num3 + LADO + BAIXO no ar`: Estrela cadente

Inimigos Menores:

**Espírito Viridente**
1. Parece um fantasma verde;
2. Arremessa folhas afiadas;
3. Conjura raízes pelo chão;
4. Bloqueia golpes com folhas?

**Falcão Possuído**
1. Olhos verdes;
2. Pouco HP;
3. Ataca com rasantes;
4. Conjura folhas afiadas com o bater das asas.

**Raíz Mágica**
1. Aparece pelo chão;
2. Pode ser cortada.

**Druída**
1. Conjura feitiços da floresta (projétil verde);
2. Conjura espíritos viridentes;
3. Conjura raízes também.

Chefes:

**Cavaleiro Sombrio**
- Cavaleiro necromante.
- Estatura parecida com a do cavaleiro.
- Invoca guerreiros do chão, enquanto se cura. 
- Ataca com sua espada. 
- Reflete ataques dos jogadores. 

**Golem Verdejante**
1. Feito de pedras e raízes;
6. Um pouco maior que o Cavaleiro;
7. Ataques como socos, chutes e saltos;
8. Ataques com raízes e arremessos de pedras;
9. Cria plataformas?

**Dragão Carmesim**
1. Bem grandão;
10. Primeiramente aparece sua pata em uma montanha, com isso o cavaleiro e o mago devem fugir enquanto se escondem das chamas do dragão.
11. Após uma escalada pela montanha, enquanto evitam as chamas, ambos encontram o dragão no topo da montanha.
12. Durante a batalha, o dragão cospe fogo, ataca com as garras e pode até bater as asas para empurrar os personagens para fora do mapa.

**Comment by alanos005** [comment]
Um jogo de plataforma 2D onde os dois jogadores incorporam dois personagens, um surdo e um cego. Os quais terão de
completar os mapas levando os objetos de um determinado lugar para outro, além de terem que se ajudar para concluir
os obstáculos postos em sua frente. Um jogo que necessitará de atenção, sincronia e inteligencia dos jogadores. A física
e a dinâmica são as principais caraterísticas desse game. 



- Um ajudar o outro
- Levar um objeto para um determinado lugar
- Surdo e Cego
- Dinâmica
- Física
- Plataforma 2D

**Comment by pedrykolas** [comment]
Armadura:
![image](https://user-images.githubusercontent.com/75922056/162439337-6707c0ac-24f0-4b9f-8828-26b802114f11.png)
![image](https://user-images.githubusercontent.com/75922056/162439440-37403ed3-1d71-4fc3-b47b-f3b46df4438b.png)
![image](https://user-images.githubusercontent.com/75922056/162439482-30c472aa-3433-405f-b62e-3531714db352.png)

Mago:
![image](https://user-images.githubusercontent.com/75922056/162439877-7200fadb-5be1-444b-9ca3-cf09d9784d9b.png)
![image](https://user-images.githubusercontent.com/75922056/162439981-535a5bc8-e566-4e81-a2d4-875214349b8f.png)

**Comment by pedrykolas** [comment]
https://twofist.itch.io/2d-rpg-singleplayer
Dar olhada
