### ISSUE TITLE
Referências do Jogo

### ISSUE THREAD

**Issue by alanos005** [El-Gato-Gordo/Jogo#2]
Artes, Modelos, Mecânicas e inspirações em geral para o Jogo.

**Comment by alanos005** [comment]
Shinobi III: Return of the Ninja Master
Super Meat Boy 
The Messenger
Dead Cells

**Comment by pedrykolas** [comment]
Dead Cells
Dark Souls
Castlevania (Clássico)
Blasphemous
Hollow Night

**Comment by pedrykolas** [comment]
![1](https://user-images.githubusercontent.com/75922056/161777235-f6799bd3-0d6b-4e97-8538-7fd54a69181a.jpg)
![2](https://user-images.githubusercontent.com/75922056/161777234-6850d4f9-87b4-4c28-8bea-2427c2bc45a9.jpg)
![3](https://user-images.githubusercontent.com/75922056/161777232-688f3804-0662-4aa4-bb82-ec1d53c7f4f1.jpg)
![4](https://user-images.githubusercontent.com/75922056/161777226-29b36425-d03a-4906-9f05-a4f940c35b7f.jpg)
![5](https://user-images.githubusercontent.com/75922056/161777223-c4edab68-9e2a-4f95-9132-2cec02f33a65.jpg)
![6](https://user-images.githubusercontent.com/75922056/161777218-0dbf12bc-624a-4090-b1a7-73fdc45d90e9.jpg)

**Comment by pedrykolas** [comment]
![image](https://user-images.githubusercontent.com/75922056/162983291-76fa90c3-3565-4ed4-bebf-0c1226ea7517.png)

**Comment by alanos005** [comment]
https://static.wikia.nocookie.net/katana-zero/images/3/37/Kissyface.gif/revision/latest?cb=20190626225721
https://64.media.tumblr.com/8d80361ed854052b921d7949e6c50eb8/tumblr_mkucb0d34z1r67h3uo1_500.gif
https://art.ngfiles.com/images/476000/476815_redlord93_the-purple-mage-casting-a-spell.gif?f1483368496
