### ISSUE TITLE
Definir e projetar tela de encerramento

### ISSUE THREAD

**Issue by CaioBongs** [El-Gato-Gordo/Jogo#30]
Assim como a tela de abertura (https://github.com/boidacarapreta/adcipt20221/issues/15), a tela de encerramento ajudará, durante o jogo, a (re)carregar os objetos das cenas, zerar placar, entre outros. São, pois, também duas subtarefas:

 Definir a tela de encerramento;
 Programar a tela de encerramento.
Depende de https://github.com/boidacarapreta/adcipt20221/issues/14, e recomenda-se fazer depois de https://github.com/boidacarapreta/adcipt20221/issues/15 .

Nos jogos baseados em texto, É um rascunho do(s) (provável(is)) fim(ns) do jogo.

**Comment by pedrykolas** [comment]
1º Tela de fim de jogo
- Pode ser o elmo e o chapéu ou manto do mago caídos no chão à frente de um fundo preto
- Botão para voltar ao menu principal e botão para voltar direto ao nível

**Comment by CaioBongs** [comment]
![background](https://user-images.githubusercontent.com/102802026/164845169-d61d1381-e2a9-4c61-929e-5fec02abe0ad.png)

**Comment by pedrykolasAlt** [comment]
![New Piskel](https://user-images.githubusercontent.com/104366549/165405709-bb2b9b33-ffa7-4007-9db6-d5e931d6f3f9.png)

**Comment by alanos005** [comment]
![fundofinal](https://user-images.githubusercontent.com/102801485/166918720-aa150a6a-165f-49c3-9296-0a031248a8c3.png)
