### ISSUE TITLE
Tocar música de fundo genérica

### ISSUE THREAD

**Issue by CaioBongs** [El-Gato-Gordo/Jogo#31]
Assim como https://github.com/boidacarapreta/adcipt20221/issues/6 e https://github.com/boidacarapreta/adcipt20221/issues/7, usar uma música da Internet sem restrições de direito autoral para tocar durante o jogo, mais especificamente uma por cena.

Depende de https://github.com/boidacarapreta/adcipt20221/issues/14, https://github.com/boidacarapreta/adcipt20221/issues/15 e https://github.com/boidacarapreta/adcipt20221/issues/16.

Nos jogos baseados em texto, esta tarefa é opcional: o uso de música ambiente para a leitura. Pode-se usar o código embutido de podcast, como por exemplo o [Anchor](https://anchor.fm/).

**Comment by CaioBongs** [comment]
https://www.youtube.com/watch?v=-_9XUJdLiaY

**Comment by pedrykolasAlt** [comment]
[MUSIC_TitleOpening.zip](https://github.com/El-Gato-Gordo/Jogo/files/8595133/MUSIC_TitleOpening.zip)
