### ISSUE TITLE
Estudar Javascript

### ISSUE THREAD

**Issue by pedrykolas** [El-Gato-Gordo/Jogo#5]
1. Ler o livro [Eloquent Javascript](https://eloquentjavascript.net/).
2. Instalar e usar diariamente o aplicativo [Grasshopper](https://grasshopper.app/).
3. Realizar os [cursos introdutórios da RocketSeat](https://www.rocketseat.com.br/discover).

**Comment by pedrykolas** [comment]
1. Ler o livro [Eloquent Javascript](https://eloquentjavascript.net/).
 2. Instalar e usar diariamente o aplicativo [Grasshopper](https://grasshopper.app/).
 3. Realizar os [cursos introdutórios da RocketSeat](https://www.rocketseat.com.br/discover).

**Comment by CaioBongs** [comment]
Resumo de estudo de JavaScript
material utilizado: https://www.youtube.com/watch?v=WcIIUmDch94

- Utilização do Node

Variáveis, operadores, estruturas de controle, função e objetos

Varíáveis podem ser de tipos numéricos ou textuais (var; let; const), const geralmente são melhores para uso geral, var e let para criação de variáveis e const constantes




operadores unarios binários e ternários: 
unários: postfix e prefix a++ e ++a respectivamente, soma +1 na variável (caso a = 3 e o comando a++ for executado teremos 4)
binários:
Aritiméticos, relacionais e lógicos: de maneira geral executa cálculos entre duas variáveis (incluindo com números genéricos e ela mesma), é possível verificar se um número é maior ou menor do que outro, exemplo: console.log(3 > 2) //isso faria o console dizer true
console.log(!(3 > 2)) //"!" inverte o que o console diz, ou seja o que é falso vira verdadeiro e vice-versa.
lógico:
let temsol = true
let estoucomdinheiro = true
let vousair = temsol || estoucomdinheiro
console.log(vousair) // isso faria o console dizer true pois as duas condições anteriores foram cumpridas.
ternário: 
let temsol = true
let estoucomdinheiro = true
let vousair = temsol || estoucomdinheiro
console.log(vousair ? 'Ebaa!' : 'chatao!') // isso faria o console dizer "ebaa!" caso se o vousair fosse verdadeira e "chatao!" caso fosse falso

let temsol = true
let estoucomdinheiro = true
let vousair = temsol || estoucomdinheiro
let resultado = vousair ? 'ebaa!' : 'chatao!'
console.log(resultado) // isso faria o mesmo que o último comando, porém utilizando uma variável a mais

Estruturas de controle:
if's, else's, true's, false's e for's: auto-explicativo, cria "e se" e "caso contrário" para criar situações de múltiplas escolhas, for's serve para criar comandos de repetição e de (armazenação de informações = arrays)



Função(function): tema essencial e extenso.
function soma(a,b) {
    console.log(a + (b || 2))
}
soma (3, 4, 5, 6, 7, 8) // esse comando faria o 3 + 4 ser somado

false ou um "vazio" pode ser utilizado para um valor padrão em strings, ou seja, ele será pulado.
comparando NaN(not a number) com qualquer coisa o torna falso
== compara valores incluindo texto e números
=== compara valores mas só interage se for do mesmo tipo (número e número ou texto e texto)
!== inverso da segunda
!= inverso da primeira
funções pode ser colocadas dentro de outras funções

function declaration: utiliza variáveis de maneira direta
function expression: usa variáveis de maneira indireta ou "anônima", cria resultados que depois podem ser utilizados como uma outra função.
